/*
 * Rekeningrijden Belgium API
 *
 * The international API for Rekeningrijden Belgium
 *
 * OpenAPI spec version: 0.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models;

/// <summary>
/// A vehicle's fuel type based on available types in RDW dataset
/// </summary>
/// <value>A vehicle's fuel type based on available types in RDW dataset</value>
[JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
public enum FuelType
{
    /// <summary>
    /// Enum PetrolEnum for Petrol
    /// </summary>
    [EnumMember(Value = "Petrol")]
    PetrolEnum = 0,
    /// <summary>
    /// Enum DieselEnum for Diesel
    /// </summary>
    [EnumMember(Value = "Diesel")]
    DieselEnum = 1,
    /// <summary>
    /// Enum ElectricityEnum for Electricity
    /// </summary>
    [EnumMember(Value = "Electricity")]
    ElectricityEnum = 2,
    /// <summary>
    /// Enum LPGEnum for LPG
    /// </summary>
    [EnumMember(Value = "LPG")]
    LPGEnum = 3,
    /// <summary>
    /// Enum CNGEnum for CNG
    /// </summary>
    [EnumMember(Value = "CNG")]
    CNGEnum = 4,
    /// <summary>
    /// Enum AlcoholEnum for Alcohol
    /// </summary>
    [EnumMember(Value = "Alcohol")]
    AlcoholEnum = 5,
    /// <summary>
    /// Enum LNGEnum for LNG
    /// </summary>
    [EnumMember(Value = "LNG")]
    LNGEnum = 6,
    /// <summary>
    /// Enum HydrogenEnum for Hydrogen
    /// </summary>
    [EnumMember(Value = "Hydrogen")]
    HydrogenEnum = 7          }